### ISSUE TITLE
Finding nearest Lat and Long from CSV

### ISSUE THREAD

**Issue by kmuddapu** [Bersaelor/KDTree#11]
I have a CSV file with all the locations . Is it possible to find the nearest location based on current location.

**Comment by Bersaelor** [comment]
Sure it is!

1. Create a struct representing your data points
2. Make your struct conform to `KDTreePoint`, thereby setting Lat and Long as your two dimensions the tree should take into consideration. (Keep in mind, your struct may have other interesting values, like `name`, `height`, `...` which you might want to store but not expose to KDTree.
3. Load your csv file into array of your structs and create a KDTree based on those values.

In fact, when you clone this repo you will find example included which is very much similar. The example has `Stars` which are also loaded from a CSV, have two dimensions (ascension & declination), and have some more interesting values which are not included into the Algorithm:
https://github.com/Bersaelor/KDTree/blob/master/Example/KDTree/Star.swift#L135

The example also includes some performance optimizations, like loading the CSV using unsafe unmanaged pointers and storing the majority of the data for the stars in a referenced `Box`. You may use those tricks too but do so at your own risk and be aware of [Premature Optimization](http://wiki.c2.com/?PrematureOptimization).
