### ISSUE TITLE
OS X support

### ISSUE THREAD

**Issue by nickswalker** [Bersaelor/KDTree#2]
No dependency on platform specific stuff so this should be straightforward. If you don't mind I'll make a PR for this.

**Comment by Bersaelor** [comment]
I'd love to add OSX, and also tvOS. Go ahead and make a PR, I can only look into it again after business hours today.

**Comment by Bersaelor** [comment]
@nickswalker I made a PR for it in a break, as I realised there is only one file that imports UIKit for the CGPoint. Does this solve your problems:
https://github.com/Bersaelor/KDTree/pull/3
?

Maybe I should add a tvOS and a OSX example target so we can see that it works as expected and duplicate the tests.
'pod lib lint' succeeds so the project builds for those platforms.

**Comment by nickswalker** [comment]
Looks good! Running the tests on all platforms would help ensure nothing becomes incompatible. [This](https://github.com/nickswalker/ASCIIfy/blob/master/Example/Podfile) or AlamoFire's would serve as a good template for this.

**Comment by Bersaelor** [comment]
Done, try with version 0.1.2.

If you have ideas for other improvements, my ears are open!
