### ISSUE TITLE
Cocoapods 0.5.2

### ISSUE THREAD

**Issue by aplusm** [Bersaelor/KDTree#25]
Hi @Bersaelor,

Could you please push an updated pod for the library with my latest pull request ?

Thanks !

**Comment by Bersaelor** [comment]
There you go: https://github.com/CocoaPods/Specs/tree/master/Specs/0/8/6/KDTree

I was planning to make the next release the `Swift4` one, but you can use this minor version for now.

**Comment by aplusm** [comment]
Thank you @Bersaelor  !
