### ISSUE TITLE
Unable to install with Carthage

### ISSUE THREAD

**Issue by JackCostigan** [Bersaelor/KDTree#51]
Currently KDTree doesn't work with Carthage. See demo project [here](https://github.com/JackCostigan/KDTreeCarthageDemo).

The carthage command fails with the error:

```
Dependency "KDTree" has no shared framework schemes for any of the platforms: iOS

If you believe this to be an error, please file an issue with the maintainers at https://github.com/Bersaelor/KDTree/issues/new
```

I beleive the issue is because Carthage is unable to find any schemes to build. I opened a PR [here](https://github.com/Bersaelor/KDTree/pull/50) to fix the issue.

Please let me know if you want any more details.

**Comment by Bersaelor** [comment]
Hey @JackCostigan , is this still an issue for you?

As the Swift Package Manager can now be used for any apple platform (and is super convenient out of xcode), I am planning to restructure the folders.
At the moment the Example app installs it's KDTree dependency via Cocoapods, but I'm planning to make it use SPM.

I'll probably also put a note into the Readme.md that cocoapods are discouraged and only supported for legacy systems, and I'll probably stop supporting cocoapods sometime next year.

Using SPM with xcode is as simple as pressing this button:
![xcode](https://user-images.githubusercontent.com/4517582/87200806-9a550900-c2fd-11ea-8b9e-cee34577fca5.jpg)

And then copying the url to this repository in.

**Comment by Bersaelor** [comment]
I checked with friends and colleagues and noone found a compelling reason not to go SPM only from now on.

So as of version 1.4.0 `KDTree` will loose the cocoapods and carthage bulk, so only the `Package.swift` has to be updated from now on.
