### ISSUE TITLE
[Feature request] forEach method

### ISSUE THREAD

**Issue by chihogoogle** [Bersaelor/KDTree#52]
Hi,

The current library already supports a lot APIs which covers most of the use cases but it would be nice if there's a forEach method defined below.

// Calls shouldEnd block starting from the nearest element to furthest element
// from the given element, until the block returns true.
func forEachNearestFrom(_ element: Element, shouldEnd: ((Element) -> Bool))

I think this would cover every case :)

Thanks!
Chiho

**Comment by Bersaelor** [comment]
Good Idea!

I don’t know if I can get too it soon, as I’m rather busy with my startup looc.io atm.
Maybe you can try creating a PR and I can help you with it?

**Comment by chihogoogle** [comment]
Sounds good to me! I can take a stab at implementing forEach. Not an urgent due to other priorities but look into it little later and send a PR once it's ready. I'll add a comment here if I need any help on understanding the data structure itself :)

**Comment by Bersaelor** [comment]
Method is available[ here]([url](https://github.com/Bersaelor/KDTree/blob/aea82f70a6456254aba339753925316d4a6acd29/Sources/KDTree.swift#L384))
