### ISSUE TITLE
add support for visionOS

### ISSUE THREAD

**Issue by GerdC** [Bersaelor/KDTree#62]
Doesn't compile for VisionOS:

```
import Foundation
#if os(macOS) || os(iOS) || os(tvOS) || os(watchOS)
    import CoreGraphics
#endif

extension CGPoint: KDTreePoint {
    public static var dimensions = 2
    
    public func kdDimension(_ dimension: Int) -> Double {
        return dimension == 0 ? Double(self.x) : Double(self.y)
    }

    public func squaredDistance(to otherPoint: CGPoint) -> Double {
        let x = self.x - otherPoint.x
        let y = self.y - otherPoint.y
        return Double(x*x + y*y)
    }
}

```

maybe adding ' || os(visionOS)' is all that is needed

to test, add 'Apple Vision' to a project, not only 'Apple Vision (designed for iPad)'

**Comment by GerdC** [comment]
I see the fix is already in master but not released. Could you release?

**Comment by Bersaelor** [comment]
Thank you for pointing this out, I completely forgot to publish a new release after the changes from last year!

**Comment by Bersaelor** [comment]
Thank you for pointing this out, I completely forgot to publish a new release after the changes from last year!
